Add osx-arm64 build
conda-forge/pmdarima-feedstock pull request #29
Opened 2022-05-29 17:02 UTC by jonashaag

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-05-29 17:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-05-29 17:02 UTC, jonashaag commented
@conda-forge-admin rerender

2022-05-29 18:04 UTC, jonashaag commented
@conda-forge-admin rerender

2022-05-29 18:06 UTC, jonashaag commented
@conda-forge-admin rerender

2022-05-29 18:19 UTC, jonashaag commented
@conda-forge-admin rerender

2022-05-29 18:33 UTC, jonashaag commented
@conda-forge-admin rerender

2022-06-14 06:12 UTC, tomasvanpottelbergh requested changes

2022-06-14 06:12 UTC, tomasvanpottelbergh commented on recipe/build.sh
> +  # basic_check_build() does not work when cross compiling
Could you add a reference here to the issue you created in the pmdarima repo?

2022-06-14 06:14 UTC, tomasvanpottelbergh commented
Sorry for the late response, but thanks a lot for making this work! Good to merge if you address my small comment.l

2022-06-14 06:19 UTC, jonashaag commented
Can you add comment and merge while you’re at it?

2022-06-14 06:27 UTC, tomasvanpottelbergh approved these changes

2022-06-14 07:37 UTC, merged